### ISSUE TITLE
zfs dataset naming scheme

### ISSUE THREAD

**Issue by mikl0s** [chyves/chyves#10]
When running `chyves dataset zroot install` on a default FreeBSD ZFS-on-root install, the mount path naming scheme is a bit off, adding the pool name to the path naming scheme.

```
zroot/chyves                692K  73.1G   104K  /chyves/zroot
zroot/chyves/.config        104K  73.1G   104K  /chyves/zroot/.config
zroot/chyves/Firmware        96K  73.1G    96K  /chyves/zroot/Firmware
zroot/chyves/ISO            192K  73.1G    96K  /chyves/zroot/ISO
zroot/chyves/ISO/null.iso    96K  73.1G    96K  /chyves/zroot/ISO/null.iso
zroot/chyves/guests         100K  73.1G   100K  /chyves/zroot/guests
zroot/chyves/logs            96K  73.1G    96K  /chyves/zroot/logs
```

That should have been without zroot in the path like this:

```
zroot/chyves                692K  73.1G   104K  /chyves
zroot/chyves/.config        104K  73.1G   104K  /chyves/.config
zroot/chyves/Firmware        96K  73.1G    96K  /chyves/Firmware
zroot/chyves/ISO            192K  73.1G    96K  /chyves/ISO
zroot/chyves/ISO/null.iso    96K  73.1G    96K  /chyves/ISO/null.iso
zroot/chyves/guests         100K  73.1G   100K  /chyves/guests
zroot/chyves/logs            96K  73.1G    96K  /chyves/logs
```

**Comment by EpiJunkie** [comment]
Thank you for the feedback. I appreciate you taking the time to raise this issue.

However I disagree, the reason I disagree is once you go add a second pool you have two different naming schemes. You have the one that owns `/chyves` and then the one that owns `/chyves/secondpool`, parsing the configuration files then becomes more convoluted. If the suggestion is to move the mountpoint of the first pool when a second pool is added, that is not so easy if any of the files are locked such as an ISO or guest disk image (!ZFS volume). Also with having the pool name in the path, it becomes easy to parse the parent pool name for a guest with `grep -H`.

I am curious to hear your side on why this is important?

Do you think changing/adding anything to the [ZFS section in the man page](https://htmlpreview.github.io/?https://raw.githubusercontent.com/chyves/chyves/master/man/chyves.8.html#ZFS) will help clarify this for others? (Also I just realized that the `chyves dataset <pool> promote` command is referenced but not actually written in code form yet. I will be resolving that as soon as I get some spare time.)

Thank you again. I do value the community's feedback.

**Comment by mikl0s** [comment]
Ahh I had not thought about a second pool, now it makes sense, and I need to RTFM (including your ZFS docs as clearly explains this) before posting :+1:

**Comment by EpiJunkie** [comment]
No worries. Thanks again for the feedback. If there are any changes that you suggest, I am open to ideas.

If there is nothing more, could you close this issue? Thank you.
