### ISSUE TITLE
chyves fails to start centos

### ISSUE THREAD

**Issue by girgen** [chyves/chyves#20]
Hi, 

I just followed the instructions for a centos guest, and downloaded the latest `CentOS-7-x86_64-Everything-1611.iso`.

- FreeBSD 11.0-p6 host
- chyves-0.2.0 from ports

It fails the same way as a "plain" bhyve, grub fails to read the XFS file system – [see Forum post](https://forums.freebsd.org/threads/58981/). chyves just stops at the grub prompt

```
grub> ls
(lvm/cl-root) (lvm/cl-swap) (hd0) (hd0,msdos2) (hd0,msdos1) (host) 
grub> ls (lvm/cl-root)/
error: not a correct XFS inode.
...
grub> ls (hd0,msdos2)/
error: unknown filesystem.
grub> ls (hd0,msdos1)/
error: not a correct XFS inode.
...
```

I tried all options for standard partition, btreefs, LVM, etc for the Centos installation. Also tride RHEL7 ISO with "plain" bhyve. 

Any ideas?

**Comment by EpiJunkie** [comment]
Could you post the output from `chyves <guest-name> get all` and `chyves version`? Could you verify the commands you used? IIRC, that ISO was tested using various filesystem formats to ensure it installed and booted fine. Thanks.

**Comment by charliewutwut** [comment]
FYI
I do not think this is a Chyves issue.
See: http://freebsd.1045724.x6.nabble.com/bhyve-centos7-td6162076.html 

Workaround (which also worked for me):
Install release "CentOS-7-x86_64-Minimal-1503-01.iso" and then upgrade to release -1611.
You can find the ISO in CentOS archive

**Comment by girgen** [comment]
True, this is a problem with grub. It works booting using UEFI and connecting using a working VNC viewer. I tried three different viewers before I got it working, and if memory serves med right it was VNC Viewer (for mac) that could successfully connect. Annoying having to use a GUI to install a unix server, tought, seems to forfeit the pruspose of unix somehow...
