### ISSUE TITLE
Unable to add ue0 interface to bridge

### ISSUE THREAD

**Issue by weeclemans** [chyves/chyves#22]
Hello.

```
# ifconfig -l
igb0 igb1 lo0 bridge0 ue0 tap50 tap0 tap51 bridge1
# chyves network bridge1 attach ue0
Critical error detected. Exiting for following reason:
 Invalid interface given: 'ue0'.
```

What do I wrong ?

**Comment by EpiJunkie** [comment]
@weeclemans, unfortunately adding wireless interfaces to the guest bridges is not supported. This is documented in the [bhyve official documentation](https://wiki.freebsd.org/bhyve):

> Q: Why can't I network VMs over a wireless host interface?
>
>A: Access points cannot determine the destination VMs and only see the host. Consider a simple pf(4) pf.conf configuration:
>
>
> nat on wlan0 from bridge0:network to any -> (bridge0)
> pass out all
> pass in all

Another option would be to use PCI pass-through of the `ue0` device to a pfSense chyves/bhyve guest and put your guests on a shared [private] bridge.
