### ISSUE TITLE
mtu not set

### ISSUE THREAD

**Issue by invisnet** [chyves/chyves#7]
The bridge interface always uses an mtu of 1500 when it's created. If the physical interface has an mtu != 1500 it can't be added to the bridge until the bridge mtu has been set by hand.

**Comment by EpiJunkie** [comment]
While reading the man page for [IF_BRIDGE(4)](https://www.freebsd.org/cgi/man.cgi?bridge(4)), I saw this:
>The MTU of the first member interface to be added is used as the bridge MTU.  All additional members are required to have exactly the same value.

So I have made some changes and will be pushing them in 0.1.7-dev. Basically I will be attaching the physical interface to the bridge first (before the tap interfaces were being attached first.), then I will be checking the MTU of the bridge and setting the MTU of the device if not '1500'. From my tests so far, this will resolve the issue described above.

**Comment by EpiJunkie** [comment]
@invisnet can you [test this](https://github.com/chyves/chyves/tree/dev) against your system and report back? You will need to destroy the bridge or reboot the host for the changes to be effective.

Thanks.

**Comment by invisnet** [comment]
Yes, I can confirm this now works properly on my system.

**Comment by EpiJunkie** [comment]
Great!

If you have any other suggestions or discover any bugs, let me know. Thanks.
